include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false
    avoid_print: false
    use_build_context_synchronously: false
    

analyzer:
  strong-mode:
    implicit-casts: true
    implicit-dynamic: true
  errors:
    avoid_dynamic_calls: ignore
    unused_import: error
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - "**/*.gen.dart"