name: scaler
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  auto_route: ^5.0.0
  cached_network_image: ^3.3.1

  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.0
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  dartz: ^0.10.1
  get_it: ^7.2.0
  dio: ^5.3.3
  shimmer: ^3.0.0
  hydrated_bloc: ^9.1.2
  very_good_analysis: ^2.4.0
  flutter_svg: ^2.0.7
  mocktail: ">=0.2.0 <2.0.0"
  test: ^1.16.0
  intl: ^0.19.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  # mockito: ^5.4.4
  bloc_test: ^9.1.7

flutter:

  uses-material-design: true
  
  assets:
    - assets/
  
  fonts:
    - family: IBMPlexSansArabic
      fonts:
        - asset: assets/fonts/IBMPlexSansArabic-Bold.ttf
        - asset: assets/fonts/IBMPlexSansArabic-ExtraLight.ttf
        - asset: assets/fonts/IBMPlexSansArabic-Light.ttf
        - asset: assets/fonts/IBMPlexSansArabic-Medium.ttf
        - asset: assets/fonts/IBMPlexSansArabic-Regular.ttf
        - asset: assets/fonts/IBMPlexSansArabic-SemiBold.ttf
        - asset: assets/fonts/IBMPlexSansArabic-Thin.ttf

